---
fixtures:
    repositories:
        ohmyzsh:
            ref: "v1.0.4"
            repo: "https://github.com/zanloy/puppet-ohmyzsh"
        stblib:
            ref: "4.12.0"
            repo: "https://github.com/puppetlabs/puppetlabs-stdlib"
    symlinks:
        vision_shells: '#{source_dir}'
