---
fixtures:
  repositories:
    stblib:
      ref: "v6.0.0"
      repo: "https://github.com/puppetlabs/puppetlabs-stdlib"
    ohmyzsh:
      ref: "v1.0.4"
      repo: "https://github.com/zanloy/puppet-ohmyzsh"
  symlinks:
    vision_shells: '#{source_dir}'
